#!/usr/bin/env python

'BEER -- the Bayesian spEEch Recognizer'


import argparse
import logging

import beer.cli.subcommands as subcommands


logging.basicConfig(format='%(levelname)s: %(message)s')
logger = logging.getLogger()
logger.setLevel(logging.INFO)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-d', '--debug', action='store_true',
                        help='show debug messages')

    subparsers = parser.add_subparsers(title='possible commands', metavar='<cmd>')
    for cmd_name in subcommands.__all__:
        cmd = getattr(subcommands, cmd_name)
        subparser = subparsers.add_parser(cmd_name, help=cmd.__doc__)
        cmd.setup(subparser)
        subparser.set_defaults(func=cmd.main)
    args = parser.parse_args()

    if args.debug:
        logger.setLevel(logging.DEBUG)
    args.func(args, logger)


if __name__ == '__main__':
    main()
